version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ets-websocket-backend
    ports:
      - "4400:4400"
    environment:
      PORT: 4400
      MONGO_URI: "mongodb://mongo:27017/evaluetonsavoir" # Utilisez ceci si aucune authentification n'est requise
      MONGO_DATABASE: evaluetonsavoir
      EMAIL_SERVICE: gmail
      SENDER_EMAIL: infoevaluetonsavoir@gmail.com
      EMAIL_PSW: 'vvml wmfr dkzb vjzb'
      JWT_SECRET: haQdgd2jp09qb897GeBZyJetC8ECSpbFJe
      VITE_BACKEND_URL: "http://10.196.10.69:4400" 
      VITE_AZURE_BACKEND_URL: "http://10.196.10.69:4400" 
    depends_on:
      - mongo
    command: npm start

  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:

