name: Glitch Deployment

on:
  push:
    branches:     
      main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
name: Checkout Repository
      uses: actions/checkout@v2

      
name: Deploy to Glitch
      run: |
        curl -X POST "https://api.glitch.com/v1/projects/<your-project-id>/git/commit/<your-branch-name>" \-H "Authorization: Bearer <your-glitch-token>"
      env:
        GLITCH_TOKEN: ${{ secrets.GLITCH_TOKEN }}