name: Glitch Deployment

on:
  push:
    branches:
      - glitch

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: repo-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          source_branch: "glitch"
          destination_repo: ${{ secrets.GLITCH_GIT_URL }}
          destination_branch: "main"
