name: Glitch Deployment

on:
  push:
    branches:
      - glitch

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: repo-sync
        uses: wei/git-sync@v1
        env:
          SOURCE_REPO: "https://github.com/ETS-PFE004-Plateforme-sondage-minitest/ETS-PFE004-EvalueTonSavoir-Backend.git"
          SOURCE_BRANCH: "glitch"
          DESTINATION_REPO: ${{ secrets.GLITCH_GIT_URL }}
          DESTINATION_BRANCH: "main"
        with:
          args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
