name: Glitch Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: run tests
        run: npm test

  repo-sync:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: repo-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          source_branch: "main"
          destination_repo: ${{ secrets.GLITCH_GIT_URL }}
          destination_branch: "main"
